const tr=document.getElementById('track'),cards=[...tr.children];cards.slice(0,3).forEach(c=>tr.appendChild(c.cloneNode(true)));let x=0,timer;
const visible=()=>innerWidth<560?1:innerWidth<850?2:3;
const step=()=>{const gap=15;return(tr.parentElement.clientWidth-gap*(visible()-1))/visible()+gap};
const move=(animate=true)=>{tr.style.transition=animate?'.55s':'none';tr.style.transform=`translateX(-${x*step()}px)`};
function advance(){x++;move();if(x===cards.length)setTimeout(()=>{x=0;move(false)},620)}
function restart(){clearInterval(timer);timer=setInterval(advance,5000)}
document.getElementById('next').onclick=()=>{advance();restart()};document.getElementById('prev').onclick=()=>{if(x<=0){x=cards.length;move(false);requestAnimationFrame(()=>requestAnimationFrame(()=>{x=cards.length-1;move()}))}else{x--;move()}restart()};addEventListener('resize',()=>move(false));move(false);restart();

const escort=document.querySelector('[data-escort-video]');if(escort){const start=13,end=19.2,play=()=>escort.play().catch(()=>{});escort.addEventListener('loadedmetadata',()=>{escort.currentTime=start;play()},{once:true});escort.addEventListener('timeupdate',()=>{if(escort.currentTime>=end||escort.currentTime<start-.2){escort.currentTime=start;play()}})}

function openModal(id){document.getElementById(id).classList.add('open');document.body.style.overflow='hidden'}function closeModal(id){document.getElementById(id).classList.remove('open');document.body.style.overflow=''}document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>closeModal(b.dataset.close));document.querySelectorAll('.modal').forEach(m=>m.onclick=e=>{if(e.target===m)closeModal(m.id)});
const catalogue=cards.map(c=>({title:c.querySelector('h3').textContent,copy:c.querySelector('p').textContent}));document.getElementById('serviceList').innerHTML=catalogue.map(s=>`<div><b>${s.title}</b><span>${s.copy}</span></div>`).join('');document.getElementById('all').onclick=()=>openModal('servicesModal');

const articles=[{meta:'SECURITY INSIGHT · 20 AUGUST 2026',title:'Five checks that strengthen security personnel deployment',body:'<p>A dependable deployment starts before a guard reaches the site. Confirm the personnel profile fits the requirement, verification is complete, site training is covered, post instructions are clear, and supervision and escalation are understood.</p>'},{meta:'SECURITY PRACTICE · 12 AUGUST 2026',title:'Designing access control around people and vehicles',body:'<p>Access control should reflect how employees, visitors, deliveries, contractors, emergency access and vehicles actually move through the site.</p>'},{meta:'SECURITY INSIGHT · 5 AUGUST 2026',title:'Why incident reporting should support action',body:'<p>Useful reporting identifies what happened, where, who was involved, what immediate action was taken, and whether follow-up actions were closed.</p>'}];document.querySelectorAll('[data-article]').forEach(card=>{const show=()=>{const a=articles[+card.dataset.article];document.getElementById('articleMeta').textContent=a.meta;document.getElementById('articleTitle').textContent=a.title;document.getElementById('articleBody').innerHTML=a.body;openModal('articleModal')};card.onclick=show;card.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();show()}}});

document.getElementById('assessmentForm').onsubmit=e=>{e.preventDefault();const d=new FormData(e.currentTarget),subject=`PYX Assessment Request - ${d.get('company')||d.get('name')}`,body=`PYX WEBSITE ASSESSMENT REQUEST\n\nName: ${d.get('name')}\nCompany: ${d.get('company')}\nWork Email: ${d.get('email')}\nMobile: ${d.get('mobile')}\nSector / Industry: ${d.get('industry')}\nCity / Site: ${d.get('location')}\nRequirement: ${d.get('requirement')}\n\nAssessment details:\n${d.get('details')}`;location.href=`mailto:msadatanwar1@gmail.com?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`};

const stats=document.querySelector('.stats');let counted=false;function count(){if(counted)return;counted=true;document.querySelectorAll('[data-count]').forEach(el=>{const target=+el.dataset.count,start=performance.now();function tick(now){const p=Math.min(1,(now-start)/1100),n=Math.floor(target*(1-Math.pow(1-p,3)));el.textContent=n.toLocaleString()+(target===57?'':'+');if(p<1)requestAnimationFrame(tick)}requestAnimationFrame(tick)})}if('IntersectionObserver'in window)new IntersectionObserver(es=>{if(es[0].isIntersecting)count()},{threshold:.1}).observe(stats);else count();
