const tr=document.getElementById('track'),cards=[...tr.children];

const signInMenu=document.querySelector('.signin');if(signInMenu){document.addEventListener('click',e=>{if(!signInMenu.contains(e.target))signInMenu.removeAttribute('open')});document.addEventListener('keydown',e=>{if(e.key==='Escape')signInMenu.removeAttribute('open')})}

const escort=document.querySelector('[data-escort-video]');if(escort){const start=13,end=19.2,play=()=>escort.play().catch(()=>{});escort.addEventListener('loadedmetadata',()=>{escort.currentTime=start;play()},{once:true});escort.addEventListener('timeupdate',()=>{if(escort.currentTime>=end||escort.currentTime<start-.2){escort.currentTime=start;play()}})}

function openModal(id){document.getElementById(id).classList.add('open');document.body.style.overflow='hidden'}function closeModal(id){document.getElementById(id).classList.remove('open');document.body.style.overflow=''}document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>closeModal(b.dataset.close));document.querySelectorAll('.modal').forEach(m=>m.onclick=e=>{if(e.target===m)closeModal(m.id)});
const catalogue=cards.map(c=>({title:c.querySelector('h3').textContent,copy:c.querySelector('p').textContent}));document.getElementById('serviceList').innerHTML=catalogue.map(s=>`<div><b>${s.title}</b><span>${s.copy}</span></div>`).join('');document.getElementById('all').onclick=()=>openModal('servicesModal');

const articles=[{meta:'SECURITY INSIGHT · 20 AUGUST 2026',title:'Five checks that strengthen security personnel deployment',body:'<p>A dependable deployment starts before a guard reaches the site. Confirm the personnel profile fits the requirement, verification is complete, site training is covered, post instructions are clear, and supervision and escalation are understood.</p>'},{meta:'SECURITY PRACTICE · 12 AUGUST 2026',title:'Designing access control around people and vehicles',body:'<p>Access control should reflect how employees, visitors, deliveries, contractors, emergency access and vehicles actually move through the site.</p>'},{meta:'SECURITY INSIGHT · 5 AUGUST 2026',title:'Why incident reporting should support action',body:'<p>Useful reporting identifies what happened, where, who was involved, what immediate action was taken, and whether follow-up actions were closed.</p>'}];document.querySelectorAll('[data-article]').forEach(card=>{const show=()=>{const a=articles[+card.dataset.article];document.getElementById('articleMeta').textContent=a.meta;document.getElementById('articleTitle').textContent=a.title;document.getElementById('articleBody').innerHTML=a.body;openModal('articleModal')};card.onclick=show;card.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();show()}}});

document.getElementById('assessmentForm').onsubmit=e=>{e.preventDefault();const d=new FormData(e.currentTarget),subject=`PYX Assessment Request - ${d.get('company')||d.get('name')}`,body=`PYX WEBSITE ASSESSMENT REQUEST\n\nName: ${d.get('name')}\nCompany: ${d.get('company')}\nWork Email: ${d.get('email')}\nMobile: ${d.get('mobile')}\nSector / Industry: ${d.get('industry')}\nCity / Site: ${d.get('location')}\nRequirement: ${d.get('requirement')}\n\nAssessment details:\n${d.get('details')}`;location.href=`mailto:msadatanwar1@gmail.com?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`};

const stats=document.querySelector('.stats');let counted=false;function count(){if(counted)return;counted=true;document.querySelectorAll('[data-count]').forEach(el=>{const target=+el.dataset.count,start=performance.now();function tick(now){const p=Math.min(1,(now-start)/1100),n=Math.floor(target*(1-Math.pow(1-p,3)));el.textContent=n.toLocaleString()+(target===57?'':'+');if(p<1)requestAnimationFrame(tick)}requestAnimationFrame(tick)})}if('IntersectionObserver'in window)new IntersectionObserver(es=>{if(es[0].isIntersecting)count()},{threshold:.1}).observe(stats);else count();

const chatLauncher=document.getElementById('chatLauncher'),chatPanel=document.getElementById('chatPanel'),chatClose=document.getElementById('chatClose'),chatMessages=document.getElementById('chatMessages'),chatForm=document.getElementById('chatForm'),chatInput=document.getElementById('chatInput');
const chatAnswers={services:'PYX provides guarding, escort and personal security, event security, access and traffic control, CCTV, electronic detection, patrol and inspection, training, information security, technology delivery and manpower services.',assessment:'I can take you to the assessment form. Please include your mobile number and type the City / Site location.',careers:'PYX welcomes profiles for security operations, technology and corporate-support roles. The Careers section has the application email link.',location:'The PYX office is at 12-A, 1st Floor, Tufail Market, opposite Cantt Courts, Tufail Road, Saddar, Lahore Cantt. The Contact section includes Google Maps.',contact:'You can call +92 42 36685320 or email info@pyxsecurity.com.'};
function chatMessage(text,type='bot'){const p=document.createElement('p');p.className=type;p.textContent=text;chatMessages.appendChild(p);chatMessages.scrollTop=chatMessages.scrollHeight}
function openChat(){chatPanel.hidden=false;chatLauncher.setAttribute('aria-expanded','true');setTimeout(()=>chatInput.focus(),0)}function closeChat(){chatPanel.hidden=true;chatLauncher.setAttribute('aria-expanded','false')}
chatLauncher.onclick=()=>chatPanel.hidden?openChat():closeChat();chatClose.onclick=closeChat;
document.querySelectorAll('[data-chat]').forEach(button=>button.onclick=()=>{const key=button.dataset.chat;chatMessage(button.textContent,'user');chatMessage(chatAnswers[key]);if(key==='assessment')setTimeout(()=>location.hash='assessment',500);if(key==='careers')setTimeout(()=>location.hash='careers',500);if(key==='location')setTimeout(()=>location.hash='contact',500)});
chatForm.onsubmit=e=>{e.preventDefault();const question=chatInput.value.trim();if(!question)return;chatMessage(question,'user');chatInput.value='';const q=question.toLowerCase();let key=q.match(/job|career|vacan|apply/) ? 'careers' : q.match(/where|address|location|map|office/) ? 'location' : q.match(/phone|email|contact|call/) ? 'contact' : q.match(/assess|quote|price|requirement|site/) ? 'assessment' : 'services';setTimeout(()=>chatMessage(chatAnswers[key]),250)};
