server {
    listen ${PORT};
    listen [::]:${PORT};
    server_name _;

    root /usr/share/nginx/html;
    index index.html;
    server_tokens off;

    location / {
        try_files $uri $uri/ =404;
    }

    location ~* \.(?:css|js|jpg|jpeg|png|gif|webp|svg|ico|woff2?)$ {
        expires 7d;
        add_header Cache-Control "public, max-age=604800";
        try_files $uri =404;
    }

    location ~* \.(?:mp4|webm)$ {
        expires 30d;
        add_header Cache-Control "public, max-age=2592000";
        try_files $uri =404;
    }
}
